config/routes.rb
Rails.application.routes.draw do
  # get 'work/index'
  # get 'work/choose_theme'
  # get 'work/display_theme'
  resources :themes
  resources :images
  resources :values
  resources :users
  resources :sessions
  get 'main/index'
  get 'main/help'
  get 'main/contacts'
  get 'main/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'main#index'
  match 'work', to: 'work#index', via: :get
  match 'signup',   to: 'users#new',            via: 'get'
  match 'signin',   to: 'sessions#new',         via: 'get'
  match 'signout',  to: 'sessions#destroy',     via: 'get'


  resources :work, only: [:index] do
    collection do
      get 'next_image'
      get 'previous_image'
      post 'save_rating'
    end
  end
end

app/models/theme.rb
class Theme < ApplicationRecord
  has_many :images
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_action :set_theme, only: %i[ show edit update destroy ]

  # GET /themes or /themes.json
  def index
    @themes = Theme.all
  end

  # GET /themes/1 or /themes/1.json
  def show
  end

  # GET /themes/new
  def new
    @theme = Theme.new
  end

  # GET /themes/1/edit
  def edit
  end

  # POST /themes or /themes.json
  def create
    @theme = Theme.new(theme_params)

    respond_to do |format|
      if @theme.save
        format.html { redirect_to theme_url(@theme), notice: "Theme was successfully created." }
        format.json { render :show, status: :created, location: @theme }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /themes/1 or /themes/1.json
  def update
    respond_to do |format|
      if @theme.update(theme_params)
        format.html { redirect_to theme_url(@theme), notice: "Theme was successfully updated." }
        format.json { render :show, status: :ok, location: @theme }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /themes/1 or /themes/1.json
  def destroy
    @theme.destroy

    respond_to do |format|
      format.html { redirect_to themes_url, notice: "Theme was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_theme
      @theme = Theme.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def theme_params
      params.require(:theme).permit(:name, :qty_items)
    end
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/views/themes/_form.html.haml
= form_for @theme do |f|
  - if @theme.errors.any?
    #error_explanation
      %h2= "#{pluralize(@theme.errors.count, "error")} prohibited this theme from being saved:"
      %ul
        - @theme.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :qty_items
    = f.number_field :qty_items
  .actions
    = f.submit 'Save'

app/views/themes/edit.html.haml
%h1 Editing theme

= render 'form'

= link_to 'Show', @theme
\|
= link_to 'Back', themes_path

app/views/themes/index.html.haml
%h1 Listing themes

%table
  %thead
    %tr
      %th Name
      %th Qty items
      %th
      %th
      %th

  %tbody
    - @themes.each do |theme|
      %tr
        %td= theme.name
        %td= theme.qty_items
        %td= link_to 'Show', theme
        %td= link_to 'Edit', edit_theme_path(theme)
        %td= link_to 'Destroy', theme, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Theme', new_theme_path

app/views/themes/new.html.haml
%h1 New theme

= render 'form'

= link_to 'Back', themes_path

app/views/themes/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @theme.name
%p
  %b Qty items:
  = @theme.qty_items

= link_to 'Edit', edit_theme_path(@theme)
\|
= link_to 'Back', themes_path