config/routes.rb
Rails.application.routes.draw do
  # get 'work/index'
  # get 'work/choose_theme'
  # get 'work/display_theme'
  resources :themes
  resources :images
  resources :values
  resources :users
  resources :sessions
  get 'main/index'
  get 'main/help'
  get 'main/contacts'
  get 'main/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'main#index'
  match 'work', to: 'work#index', via: :get
  match 'signup',   to: 'users#new',            via: 'get'
  match 'signin',   to: 'sessions#new',         via: 'get'
  match 'signout',  to: 'sessions#destroy',     via: 'get'


  resources :work, only: [:index] do
    collection do
      get 'next_image'
      get 'previous_image'
      post 'save_rating'
    end
  end
end

app/models/image.rb
class Image < ApplicationRecord

  belongs_to :theme
  has_many :values, dependent: :destroy  # Добавьте эту строку

  # get images array of arrays by given theme_id
  scope :theme_images, -> (theme_id) {
    select('id','name','file','ave_value').where(theme_id: theme_id)
  }

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: %i[ show edit update destroy ]

  # GET /images or /images.json
  def index
    @images = Image.all
  end

  # GET /images/1 or /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images or /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to image_url(@image), notice: "Image was successfully created." }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1 or /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to image_url(@image), notice: "Image was successfully updated." }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1 or /images/1.json
  def destroy
    @image.destroy

    respond_to do |format|
      format.html { redirect_to images_url, notice: "Image was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def image_params
      params.require(:image).permit(:name, :file, :ave_value, :theme_id)
    end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.haml
= form_for @image do |f|
  - if @image.errors.any?
    #error_explanation
      %h2= "#{pluralize(@image.errors.count, "error")} prohibited this image from being saved:"
      %ul
        - @image.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :file
    = f.text_field :file
  .field
    = f.label :ave_value
    = f.text_field :ave_value
  .field
    = f.label :theme_id
    = f.number_field :theme_id
  .actions
    = f.submit 'Save'

app/views/images/edit.html.haml
%h1 Editing image

= render 'form'

= link_to 'Show', @image
\|
= link_to 'Back', images_path

app/views/images/index.html.haml
%h1 Listing images

%table
  %thead
    %tr
      %th Name
      %th File
      %th Ave value
      %th Theme
      %th
      %th
      %th

  %tbody
    - @images.each do |image|
      %tr
        %td= image.name
        %td= image_tag("/#{image.file}", width: '100')
        %td= image.ave_value
        %td= image.theme_id
        %td= link_to 'Show', image
        %td= link_to 'Edit', edit_image_path(image)
        %td= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Image', new_image_path

app/views/images/new.html.haml
%h1 New image

= render 'form'

= link_to 'Back', images_path

app/views/images/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @image.name
%p
  %b File:
  = image_tag("pictures/#{@image.file}", width: '200')

%p
  %b Ave value:
  = @image.ave_value
%p
  %b Theme:
  = @image.theme_id

= link_to 'Edit', edit_image_path(@image)
\|
= link_to 'Back', images_path